// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monuments.API.DbContexts;

#nullable disable

namespace Monuments.API.Migrations
{
    [DbContext(typeof(MonumentsDbContext))]
    partial class MonumentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Monuments.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slogan")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abia",
                            Slogan = "God's Own State"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bauchi",
                            Slogan = "Pearl of Tourism"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lagos",
                            Slogan = "Center of Excellence"
                        });
                });

            modelBuilder.Entity("Monuments.API.Entities.Monument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Monuments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "A UNESCO World Heritage site featuring the Palace of the Hidi.",
                            Name = "Sukur Cultural Landscape"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Ancient earthworks and one of the world's largest man-made earthworks.",
                            Name = "Benin City Walls and Moat"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Nigeria's first-storey building built in 1845.",
                            Name = "First Storey Building"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "A UNESCO World Heritage site featuring the Palace of the Hidi.",
                            Name = "Sukur Cultural Landscape"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Historic walls and the palace of the Emir.",
                            Name = "Ancient Kano City Walls & Gidan Makama"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "Exhibits relics from the Civil War and Nigerian military history.",
                            Name = "National War Museum"
                        });
                });

            modelBuilder.Entity("Monuments.API.Entities.Monument", b =>
                {
                    b.HasOne("Monuments.API.Entities.City", "City")
                        .WithMany("Monuments")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Monuments.API.Entities.City", b =>
                {
                    b.Navigation("Monuments");
                });
#pragma warning restore 612, 618
        }
    }
}
